// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BotInterface is an autogenerated mock type for the BotInterface type
type BotInterface struct {
	mock.Mock
}

// SuccsesAuth provides a mock function with given fields: id, username
func (_m *BotInterface) SuccsesAuth(id int64, username string) error {
	ret := _m.Called(id, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = rf(id, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBotInterface creates a new instance of BotInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBotInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BotInterface {
	mock := &BotInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
